<a href="https://colab.research.google.com/github/VKline333/Statistics/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
samples =np.random.normal(100,15,1000)
samples

array([111.73823085,  96.68275764,  73.47027597, 103.86179816,
        90.92701647, 117.88391123, 105.11889891,  81.1734473 ,
       138.22769011, 142.77281337,  96.64523151, 101.34700702,
        91.00389659,  92.16516019,  84.3156917 , 132.73051555,
        93.77251704, 119.43321282,  67.86936798, 102.53959904,
        94.12202655, 103.42401727, 123.26195283,  94.81634168,
       129.10829237, 106.56436562, 103.65510256, 104.86069308,
       110.89037529, 114.30066534,  99.55794143,  88.05617052,
        90.37659251, 101.91289546, 108.34209916, 104.38981026,
       107.51585255,  96.53320412, 100.24466403,  82.5635611 ,
        89.43839295, 116.53359836, 113.28105419, 132.61827408,
        73.98698161, 101.97964783,  89.08783335,  60.08065815,
       118.54837109, 104.98199981, 104.45241359, 103.35321445,
       102.81814361, 102.97792707, 113.32568222,  79.57297427,
       108.1410486 , 112.85869236, 102.01852422,  60.87835483,
        97.60290056, 100.66104242,  87.90964009,  94.01

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)

In [ ]:
mean

100.4708492569046

In [ ]:
median

100.72422844991448

In [ ]:
mode

ModeResult(mode=array([54.36915257]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples,25)
q3 = np.percentile(samples,75)
iqr = q3 - q1

In [ ]:
min

54.36915256618231

In [ ]:
max

145.93439477496398

In [ ]:
q1

90.78199850322225

In [ ]:
q3

110.64342337105236

In [ ]:
iqr

19.86142486783011

Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
std_dev = np.std(samples)

In [ ]:
variance

227.045642627979

In [ ]:
std_dev

15.068033800996698

Compute the **skewness** and **kurtosis**

In [ ]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)

In [ ]:
skewness

-0.06476531991402644

In [ ]:
kurtosis

0.03795101034289994

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [3]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [6]:
y = np.random.randint(100, size=10)
y

array([47, 50, 48,  1, 18, 84, 22, 50, 54, 20])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [7]:
r = np.corrcoef(x,y)
r

array([[ 1.        , -0.05818279],
       [-0.05818279,  1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
np.corrcoef(tips["total_bill"],tips["tip"])

array([[1.        , 0.67573411],
       [0.67573411, 1.        ]])